// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

/** 公会任务数据结构 */
declare namespace HttpGuildTaskModel {

   /** 公会任务排行榜 */
   export interface GuildTask {
       /** 公会id */
       guildId: number;
       /** 结算时的公会等级 */
       level: number;
       /** 公会分组id */
       groupId: string;
       /** 公会分组任务类型 */
       groupTaskType: string;
   }

   /** 公会任务排行榜分组信息 */
   export interface GuildTaskGroup {
       /** 分组id */
       id?: string;
       /** 分组等级 */
       level: number;
       /** 所有公会id */
       guildIds: number[];
       /** 任务类型 */
       taskType: string;
       /** 分组索引 */
       groupIndex: number;
   }

   /** 公会任务信息（由GuildTask和Guild组合出的结构） */
   export interface GuildTaskInfo {
       /** 公会id */
       guildId: number;
       /** 公会头像 */
       avatar: string;
       /** 公会名字 */
       name: string;
       /** 上一届公会等级(仅结算期间返回值) */
       lastLevel: number;
       /** 公会等级 */
       level: number;
       /** 分组id */
       groupId?: string;
       /** 分组任务类型 */
       groupTaskType?: string;
       /** 任务积分 */
       score: number;
   }

   /** 公会任务小组信息 */
   export interface RspGuildTaskGroup {
       /** 分组信息 */
       group?: GuildTaskGroup;
       /** 小组列表 */
       guilds?: GuildTaskInfo[];
       /** 是否上一届的数据 */
       isLast: boolean;
   }

}