// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

import { HttpRequest } from "../../../module/network/HttpRequest";
import { GameWebTool } from "../GameWebTool";

/** 玩家账户接口 */
export class HttpAccount {

    private static get Url() { return `${mGameSetting.serverUrl}/account/${mGameSetting.gameCode}/`; }

    /** 获取玩家账户 */
    public static async getAccount(userId: string) {
        let url = this.Url + `get?userId=${userId}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse<HttpAccountModel.Account>;
        if (result?.code == 0) {
            return result.data;
        } else {
            mLogger.error(result);
            return null;
        }
    }

    /** 创建玩家账户 */
    public static async createAccount(reqData: HttpAccountModel.ReqAccount) {
        let url = this.Url + `create`;
        let result = await HttpRequest.requestObject(url, { method: "POST", data: reqData, header: GameWebTool.gameCodeHeader }) as MResponse;
        if (result?.code == 0) {
            return true;
        } else {
            mLogger.error(result);
            return false;
        }
    }

    /** 添加白名单账户 (多个用户id使用;隔开) */
    public static async addWhiteListAccount(key: string, userId: string) {
        let url = this.Url + `add_white?key=${key}&userId=${userId}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse;
        if (result?.code == 0) {
            return true;
        } else {
            mLogger.error(result);
            return false;
        }
    }

    /** 移除白名单账户 (多个用户id使用;隔开) */
    public static async deleteWhiteListAccount(key: string, userId: string) {
        let url = this.Url + `del_white?key=${key}&userId=${userId}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse;
        if (result?.code == 0) {
            return true;
        } else {
            mLogger.error(result);
            return false;
        }
    }

    /** 是否白名单账户 */
    public static async getAllWhiteListAccount(key: string) {
        let url = this.Url + `get all_white?key=${key}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse<string[]>;
        if (result?.code == 0) {
            return result.data;
        } else {
            mLogger.error(result);
            return null;
        }
    }

    /** 是否白名单账户 */
    public static async isWhiteListAccount(key: string, userId: string) {
        let url = this.Url + `is_white?key=${key}&userId=${userId}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse;
        return result;
    }

}