// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

import { HttpRequest } from "../../../module/network/HttpRequest";
import { GameWebTool } from "../GameWebTool";

/** 玩家账户接口 */
export class HttpAccount {

    private static get Url() { return `${mGameSetting.serverUrl}/account/${mGameSetting.gameCode}/`; }

    /** 获取玩家账户 */
    public static async getAccount(userId: string) {
        let url = this.Url + `get?userId=${userId}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse<HttpAccountModel.Account>;
        if (result?.code == 0) {
            return result.data;
        } else {
            mLogger.error(result);
            return null;
        }
    }

    /** 创建玩家账户 */
    public static async createAccount(reqData: HttpAccountModel.ReqAccount) {
        let url = this.Url + `create`;
        let result = await HttpRequest.requestObject(url, { method: "POST", data: reqData, header: GameWebTool.gameCodeHeader }) as MResponse;
        if (result?.code == 0) {
            return true;
        } else {
            mLogger.error(result);
            return false;
        }
    }

}