// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

/** 玩家账户数据结构 */
declare namespace HttpAccountModel {

   /** 用户账号 */
   export interface Account {
       /** 用户id */
       userId: string;
       /** 用户来源 */
       origin?: string;
       /** 注册ip地址 */
       ip?: string;
       /** 创建时间 */
       createTime?: string;
   }

   /** 请求 创建用户账号 */
   export interface ReqAccount {
       /** 用户id */
       userId: string;
       /** 用户来源 */
       origin?: string;
       /** 注册ip地址 */
       ip?: string;
   }

   /** 自定义的异常 */
   export interface CustExecption {
       /** id */
       id: string;
       /** 异常信息 */
       message: string;
       /** 备注 */
       commit: string;
       /** 创建时间 */
       createTime: string;
   }

}