// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

/** 公会数据结构 */
declare namespace HttpGuildModel {

   /** 公会 */
   export interface Guild {
       /** 公会id */
       guildId?: number;
       /** 会长id */
       owner?: string;
       /** 公会头像 */
       avatar?: string;
       /** 公会名字 */
       name: string;
       /** 公会简介 */
       desc?: string;
       /** 扩展参数 */
       extParam?: string;
       /** 公会分数1 */
       score1?: number;
       /** 公会分数2 */
       score2?: number;
       /** 公会周分数 */
       weekScore?: number;
       /** 公会月分数 */
       monthScore?: number;
       /** 成员数量限制 */
       memberLimit: number;
       /** 成员加入条件限制 */
       condLimit?: string;
       /** 加入方式 0自由加入 1需要审核 */
       joinMethod: number;
       /** 当前成员数量 */
       memberNum?: number;
   }

   /** 公会聊天消息 */
   export interface GuildChat {
       /** 消息id */
       id?: string;
       /** 公会id */
       guildId: number;
       /** 用户id */
       userId: string;
       /** 聊天消息内容 */
       content: string;
       /** 消息类型 */
       type?: string;
       /** 消息类型值 */
       value?: number;
       /** 扩展参数 */
       extParam?: string;
       /** 消息发送的时间戳 */
       time?: number;
   }

   /** 公会聊天消息 (由PlayInfo和GuildChat组合出的结构) */
   export interface GuildChatInfo {
       /** 消息id */
       id?: string;
       /** 用户id */
       userId?: string;
       /** 聊天消息内容 */
       content?: string;
       /** 消息类型 */
       type?: string;
       /** 消息类型值 */
       value?: number;
       /** 扩展参数 */
       extParam?: string;
       /** 消息发送的时间戳 */
       time?: number;
       /** 头像 */
       avatar?: string;
       /** 名字 */
       name?: string;
   }

   /** 公会成员 */
   export interface GuildMember {
       /** 用户id */
       userId: string;
       /** 公会id */
       guildId?: number;
       /** 权限等级(0-99 99权限最高为公会会长 0为普通成员, >=10的成员可以审核新成员加入) */
       privilege?: number;
       /** 申请加入的公会id */
       approves: number[];
   }

   /** 公会成员信息 (由PlayInfo和GuildMember组合出的结构) */
   export interface GuildMemberInfo {
       /** 用户id */
       userId: string;
       /** 头像 */
       avatar?: string;
       /** 名字 */
       name?: string;
       /** vip等级 */
       vip?: number;
       /** 玩家等级 */
       level?: number;
       /** 玩家关卡 */
       stage?: string;
       /** 扩展参数 */
       extParam?: string;
       /** 权限等级(0-99 99权限最高为公会会长 0为普通成员, >=10的成员可以审核新成员加入) */
       privilege?: number;
   }

   /** 请求 创建公会 */
   export interface ReqCreateGuild {
       /** 公会信息 */
       guild: Guild;
       /** 用户id */
       userId: string;
   }

   /** 请求 退出公会 */
   export interface ReqExitGuild {
       /** 玩家id */
       userId: string;
   }

   /** 请求 处理公会审批 */
   export interface ReqGuildApprove {
       /** 用户id */
       userId: string;
       /** 审核用户id */
       approveId: string;
       /** 审核结果 */
       approveResult: boolean;
   }

   /** 请求 获取公会审批信息列表 */
   export interface ReqGuildApproveList {
       /** 公会id */
       guildId: number;
       /** 每页显示数量 */
       pageSize: number;
       /** 第几页的数据 */
       pageNumber: number;
   }

   /** 请求 聊天列表 */
   export interface ReqGuildChatList {
       /** 公会id */
       guildId: number;
       /** 消息类型 */
       type?: string;
       /** 发送时间 (传值表示只获取这个时间之后的消息) */
       time?: number;
   }

   /** 请求 聊天列表 */
   export interface ReqGuildChatList2 {
       /** 公会id */
       guildId: number;
       /** 用户id */
       userId?: string;
       /** 消息类型 */
       type?: string;
       /** 发送时间 (传值表示只获取这个时间之后的消息) */
       time?: number;
       /** 每页显示数量 */
       pageSize: number;
       /** 第几页的数据 */
       pageNumber: number;
   }

   /** 请求 获取公会列表 */
   export interface ReqGuildList {
       /** 数据筛选类型(可通过按位或传入多个条件) 0:不做任何筛选 1:成员未满 2:可自由加入 4:公会名模糊查找 */
       filter: number;
       /** 公会名字关键词 filter包含4时必传 */
       keyword?: string;
       /** 数据排序字段 不传表示不排序 */
       sortField?: string;
       /** 是否从小到大排序 默认从大到小 sortField传值时必传 */
       sortAscending?: boolean;
       /** 每页显示数量 */
       pageSize: number;
       /** 第几页的数据 */
       pageNumber: number;
   }

   /** 请求 获取公会成员列表 */
   export interface ReqGuildMemberList {
       /** 公会id */
       guildId: number;
       /** 每页显示数量 */
       pageSize: number;
       /** 第几页的数据 */
       pageNumber: number;
   }

   /** 请求 加入公会 */
   export interface ReqJoinGuild {
       /** 公会id */
       guildId: number;
       /** 玩家id */
       userId: string;
   }

   /** 请求 踢出公会 */
   export interface ReqKickGuild {
       /** 玩家id */
       userId: string;
       /** 踢出玩家id */
       kickId: string;
   }

   /** 请求 发送公会聊天信息 */
   export interface ReqSendGuildChat {
       /** 用户id */
       userId: string;
       /** 聊天消息内容 */
       content: string;
       /** 消息类型 选填 */
       type?: string;
       /** 消息类型值 选填 */
       value?: number;
       /** 扩展参数 */
       extParam?: string;
       /** 是否系统消息 (在玩家退出后不会被删除) */
       sysMsg?: boolean;
   }

   /** 请求 转让公会 */
   export interface ReqTransferGuild {
       /** 玩家id */
       userId: string;
       /** 转让玩家id */
       transferId: string;
   }

   /** 请求 更新公会 */
   export interface ReqUpdateGuild {
       /** 公会id */
       guildId: number;
       /** 公会头像 */
       avatar?: string;
       /** 公会名字 */
       name?: string;
       /** 公会简介 */
       desc?: string;
       /** 扩展参数 */
       extParam?: string;
       /** 公会分数1 */
       score1?: number;
       /** 公会分数2 */
       score2?: number;
       /** 公会周分数 */
       weekScore?: number;
       /** 公会月分数 */
       monthScore?: number;
       /** 成员数量限制 */
       memberLimit?: number;
       /** 成员加入条件限制 */
       condLimit?: string;
       /** 加入方式 0自由加入 1需要审核 */
       joinMethod?: number;
   }

   /** 请求 更新公会聊天信息 */
   export interface ReqUpdateGuildChat {
       /** 消息id */
       id: string;
       /** 消息类型 选填 */
       type?: string;
       /** 消息类型值 选填 */
       value?: number;
       /** 扩展参数 */
       extParam?: string;
   }

   /** 请求 更新公会成员信息 */
   export interface ReqUpdateGuildMember {
       /** 用户id */
       userId: string;
       /** 权限等级(0-99 99权限最高为公会会长 0为普通成员, >=10的成员可以审核新成员加入) */
       privilege?: number;
   }

   /** 请求 更新公会积分 */
   export interface ReqUpdateGuildScore {
       /** 公会id */
       guildId: number;
       /** 积分字段名 */
       field: string;
       /** 积分变化值 */
       value: number;
   }

   /** 响应 公会聊天信息列表 */
   export interface RspGuildChatList {
       /** 公会聊天信息列表 */
       chats: GuildChatInfo[];
       /** 每页显示数量 */
       pageSize: number;
       /** 第几页的数据 */
       pageNumber: number;
       /** 总共数量 */
       totalCount: number;
   }

   /** 响应 公会列表 */
   export interface RspGuildList {
       /** 公会列表 */
       guilds: Guild[];
       /** 每页显示数量 */
       pageSize: number;
       /** 第几页的数据 */
       pageNumber: number;
       /** 总共数量 */
       totalCount: number;
   }

   /** 响应 公会成员列表 */
   export interface RspGuildMemberList {
       /** 成员列表 */
       members: GuildMemberInfo[];
       /** 每页显示数量 */
       pageSize: number;
       /** 第几页的数据 */
       pageNumber: number;
       /** 总共数量 */
       totalCount: number;
   }

   /** 响应 我的公会信息 */
   export interface RspMyGuild {
       /** 公会信息 */
       guild?: Guild;
       /** 我的信息 */
       my?: GuildMember;
   }

}