// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

/** 游戏活动数据结构 */
declare namespace HttpActivityModel {

   /** 游戏活动 (可配置两段时间，两段时间不可交叉) */
   export interface GameActivity {
       /** 活动名字(唯一,不可重复) */
       name: string;
       /** 开始时间(使用Cron表达式) */
       cronStart: string;
       /** 结束时间(使用Cron表达式) */
       cronEnd: string;
       /** 开始时间2(使用Cron表达式) */
       cronStart2?: string;
       /** 结束时间2(使用Cron表达式) */
       cronEnd2?: string;
       /** 活动配置的时间相对UTC时间偏移的小时数 默认为北京时间+8 */
       utcOffset?: number;
       /** 活动描述 */
       desc?: string;
       /** 活动类型 */
       type?: string;
       /** 扩展参数 */
       extParam?: string;
       /** 活动开启次数 */
       loops?: number;
       /** 活动当前状态 0:等待开始 1:进行中 (服务端专用属性) */
       status?: number;
   }

   /** 游戏活动信息 */
   export interface GameActivityInfo {
       /** 活动名字(唯一,不可重复) */
       name: string;
       /** 活动描述 */
       desc: string;
       /** 活动类型 */
       type: string;
       /** 扩展参数 */
       extParam: string;
       /** 开始时间戳 */
       startTime: number;
       /** 结束时间戳 */
       endTime: number;
       /** 活动开启次数 */
       loops: number;
       /** 活动是否进行中 */
       isActive: boolean;
       /** Cron表达式释义 */
       cronDesc: string;
   }

}