// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

import { HttpRequest } from "../../../module/network/HttpRequest";
import { GameWebTool } from "../GameWebTool";

/** 游戏活动接口 */
export class HttpActivity {

    private static get Url() { return `${mGameSetting.serverUrl}/activity/${mGameSetting.gameCode}/`; }

    /** 创建活动 */
    public static async createActivity(reqData: HttpActivityModel.GameActivity) {
        let url = this.Url + `create`;
        let result = await HttpRequest.requestObject(url, { method: "POST", data: reqData, header: GameWebTool.gameCodeHeader }) as MResponse;
        if (result?.code == 0) {
            return true;
        } else {
            mLogger.error(result);
            return false;
        }
    }

    /** 删除活动 */
    public static async deleteActivity(name: string) {
        let url = this.Url + `delete?name=${name}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse;
        if (result?.code == 0) {
            return true;
        } else {
            mLogger.error(result);
            return false;
        }
    }

    /** 获取指定活动 */
    public static async getActivity(name: string) {
        let url = this.Url + `get?name=${name}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse<HttpActivityModel.GameActivityInfo>;
        if (result?.code == 0) {
            return result.data;
        } else {
            mLogger.error(result);
            return null;
        }
    }

    /** 获取所有活动 */
    public static async getAllActivity() {
        let url = this.Url + `get_all`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse<HttpActivityModel.GameActivityInfo[]>;
        if (result?.code == 0) {
            return result.data;
        } else {
            mLogger.error(result);
            return null;
        }
    }

    /** 获取所有生效的活动 */
    public static async getAllValidActivity() {
        let url = this.Url + `get_all_valid`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse<HttpActivityModel.GameActivityInfo[]>;
        if (result?.code == 0) {
            return result.data;
        } else {
            mLogger.error(result);
            return null;
        }
    }

}