// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

import { HttpRequest } from "../../../module/network/HttpRequest";
import { GameWebTool } from "../GameWebTool";

/** 杂项接口 */
export class HttpMisc {

    private static get Url() { return `${mGameSetting.serverUrl}/misc/`; }

    /** 获取服务器时间 */
    public static async time() {
        let url = this.Url + `time`;
        let result = await HttpRequest.requestObject(url, { method: "POST" }) as MResponse<number>;
        if (result?.code == 0) {
            return result.data;
        } else {
            mLogger.error(result);
            return null;
        }
    }

    /** 上报一些异常 */
    public static execption(reqData: HttpMiscModel.ReqCustExecption) {
        let url = this.Url + `${mGameSetting.gameCode}/execption`;
        HttpRequest.request(url, { method: "POST", data: reqData, header: GameWebTool.gameCodeHeader });
    }

    /** 生成二维码(Base64格式) */
    public static async genQRCode(text: string) {
        let url = this.Url + `gen_qrcode?text=${text}`;
        let result = await HttpRequest.requestObject(url, { method: "POST" }) as MResponse<string>;
        if (result?.code == 0) {
            return result.data;
        } else {
            mLogger.error(result);
            return null;
        }
    }

}