// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

/** 杂项数据结构 */
declare namespace HttpMiscModel {

   /** 请求 添加一个自定义异常 */
   export interface ReqCustExecption {
       /** 异常信息 */
       message: string;
       /** 备注 */
       commit: string;
   }

}