// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

/** 内购数据结构 */
declare namespace HttpPurchaseModel {

   /** 订单数据 */
   export interface PurchaseData {
       /** 下单时传入的自定义游戏订单 */
       orderId: string;
       /** 订单号(渠道或SDK提供的订单号) */
       sdkOrderId: string;
       /** 用户ID */
       uid: string;
       /** 商品Id */
       productId: string;
       /** 支付金额 */
       price: string;
       /** 下单时传递的扩展参数，原样返回 */
       extraParam: string;
       /** 订单创建时间 */
       createTime: string;
       /** 订单是否完成 */
       isUsed: boolean;
   }

   /** 响应 未完成订单 */
   export interface RspUnusedOrder {
       /** 自定义游戏订单 */
       orderId: string;
       /** 商品Id */
       productId: string;
   }

}