// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

import { HttpRequest } from "../../../module/network/HttpRequest";
import { GameWebTool } from "../GameWebTool";

/** 事件上报接口 */
export class HttpTrackEvent {

    private static get Url() { return `${mGameSetting.serverUrl}/gameevent/${mGameSetting.gameCode}/`; }

    /** 事件上报 */
    public static reportEvent(reqData: HttpTrackEventModel.TrackEvent) {
        let url = this.Url + `reportevt`;
        HttpRequest.request(url, { method: "POST", data: reqData, header: GameWebTool.gameCodeHeader });
    }

}