// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

/** 事件上报数据结构 */
declare namespace HttpTrackEventModel {

   /** 事件上报数据 */
   export interface TrackEvent {
       /** 事件名 */
       eventName: string;
       /** 参数 */
       param?: string;
       /** 求和 */
       sum?: number;
   }

}