// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

/** 抖音小游戏数据结构 */
declare namespace HttpDouYinModel {

   /** 抖音场景检查数据 */
   export interface DouYinSceneCheckData {
       /** 玩家openid */
       openId: string;
       /** 场景类型 */
       type?: string;
       /** 黑名单生效的时间(过了这个时间本条数据就无效了) */
       effectiveTimeS: number;
   }

   /** 请求 图片安全校验 */
   export interface ReqDouYinImageSecCheck {
       /** 为避免其它地方获取的accessToken失效,可以选择复用 */
       accessToken?: string;
       /** 需检测的图片Url */
       image: string;
   }

   /** 请求 文本安全校验 */
   export interface ReqDouYinMsgSecCheck {
       /** 为避免其它地方获取的accessToken失效,可以选择复用 */
       accessToken?: string;
       /** 需检测的文本内容 */
       content: string;
   }

   /** 请求 抖音使用礼包码兑换奖励 */
   export interface ReqDouYinVerifyGiftCode {
       /** 为避免其它地方获取的accessToken失效,可以选择复用 */
       accessToken?: string;
       /** 小游戏完成道具礼包领取后，开发者核销用户的礼包码（长度64字节以内） */
       giftCode: string;
       /** 用户的openid */
       openId: string;
       /** 每次请求都需要使用不同的 uuid（长度64字节以内） */
       uuid: string;
       /** 可以使用env_type以隔离生产环境，development:调试环境 production:线上环境 */
       envType: string;
   }

   /** 响应 抖音获取AccessToken */
   export interface RspDouYinAccessToken {
       /** 获取到的凭证 */
       data: RspDouYinAccessTokenData;
       /** 错误码 */
       err_no: number;
       /** 错误信息 */
       err_tips?: string;
   }

   /** AccessToken数据 */
   export interface RspDouYinAccessTokenData {
       /** 获取的access_token */
       access_token: string;
       /** access_token 有效时间，单位：秒 */
       expires_in: number;
       /**  access_token 过期时间戳 */
       expires_at: number;
   }

}