// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

import { HttpRequest } from "../../../module/network/HttpRequest";
import { GameWebTool } from "../GameWebTool";

/** 轮询任务接口 */
export class HttpPolling {

    private static get Url() { return `${mGameSetting.serverUrl}/polling/${mGameSetting.gameCode}/`; }

    /** 发起轮询任务 */
    public static async newPolling(key: string) {
        let url = this.Url + `new_polling?key=${key}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse<HttpPollingModel.PollingData>;
        if (result?.code == 0) {
            return result.data;
        } else {
            mLogger.error(result);
            return null;
        }
    }

    /** 删除一个轮询任务 */
    public static deletePolling(id: string) {
        let url = this.Url + `delete_polling?id=${id}`;
        HttpRequest.request(url, { method: "POST", header: GameWebTool.gameCodeHeader });
    }

    /** 更新轮询任务(设置任务的value用于轮询) */
    public static async updatePolling(id: string, value: string) {
        let url = this.Url + `update_polling?id=${id}&value=${value}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse;
        return result;
    }

    /** 轮询任务是否完成(返回value并删除本条数据) */
    public static async polling(id: string) {
        let url = this.Url + `polling?id=${id}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse;
        return result;
    }

}