// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

/** 轮询任务数据结构 */
declare namespace HttpPollingModel {

   /** 轮询任务数据 */
   export interface PollingData {
       /** id */
       id?: string;
       /** 任务类型 */
       key: string;
       /** 任务值,不为空表示任务成功 */
       value?: string;
       /** 过期时间 */
       expireTime: number;
   }

}