// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

import { HttpRequest } from "../../../module/network/HttpRequest";
import { GameWebTool } from "../GameWebTool";

/** GM数据存档接口 */
export class HttpGmData {

    private static get Url() { return `${mGameSetting.serverUrl}/gmdata/${mGameSetting.gameName}/`; }

    /** 上传GM数据存档 */
    public static async saveGmData(reqData: HttpGmDataModel.GmData) {
        let url = this.Url + `save_gmdata`;
        let result = await HttpRequest.requestObject(url, { method: "POST", data: reqData, header: GameWebTool.gameNameHeader }) as MResponse;
        if (result?.code == 0) {
            return true;
        } else {
            mLogger.error(result);
            return false;
        }
    }

    /** 删除GM数据存档 */
    public static async delGmData(id: string) {
        let url = this.Url + `del_gmdata?id=${id}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameNameHeader }) as MResponse;
        if (result?.code == 0) {
            return true;
        } else {
            mLogger.error(result);
            return false;
        }
    }

    /** 获取所有GM数据存档 */
    public static async getGmDatas() {
        let url = this.Url + `get_gmdatas`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameNameHeader }) as MResponse<HttpGmDataModel.GmData[]>;
        if (result?.code == 0) {
            return result.data;
        } else {
            mLogger.error(result);
            return null;
        }
    }

}