// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

/** GM数据存档数据结构 */
declare namespace HttpGmDataModel {

   /** GM数据 */
   export interface GmData {
       /** id */
       id?: string;
       /** 存档数据 */
       data: string;
       /** 备注 */
       commit?: string;
       /** 创建时间 */
       createTime?: number;
   }

}