// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

/** 公会排位赛数据结构 */
declare namespace HttpGuildMatchModel {

   /** 公会赛事 */
   export interface GuildMatch {
       /** 公会id */
       guildId: number;
       /** 公会分组id */
       groupId: string;
   }

   /** 公会排行榜分组信息 */
   export interface GuildMatchGroup {
       /** 分组id */
       id?: string;
       /** 分组等级 */
       level: number;
       /** 所有公会id */
       guildIds: number[];
       /** 分组索引 */
       groupIndex: number;
       /** 分组人数 */
       count: number;
   }

   /** 公会赛事信息（由GuildMatch和Guild组合出的结构） */
   export interface GuildMatchInfo {
       /** 公会id */
       guildId: number;
       /** 公会头像 */
       avatar: string;
       /** 公会名字 */
       name: string;
       /** 公会等级 */
       level: number;
       /** 公会分组id */
       groupId?: string;
       /** 积分 */
       score: number;
   }

   /** 公会排位赛信息 */
   export interface RspGuildMatchAll {
       /** 公会列表 */
       guilds?: GuildMatchInfo[];
       /** 是否上一届的数据 */
       isLast: boolean;
   }

   /** 公会排位赛小组信息 */
   export interface RspGuildMatchGroup {
       /** 分组信息 */
       group?: GuildMatchGroup;
       /** 小组列表 */
       guilds?: GuildMatchInfo[];
       /** 是否上一届的数据 */
       isLast: boolean;
   }

}