// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

import { HttpRequest } from "../../../module/network/HttpRequest";
import { GameWebTool } from "../GameWebTool";

/** 公会排位赛接口 */
export class HttpGuildMatch {

    private static get Url() { return `${mGameSetting.serverUrl}/guildmatch/${mGameSetting.gameCode}/`; }

    /** 加入排位赛 */
    public static join(guildId: number) {
        let url = this.Url + `join?guildId=${guildId}`;
        HttpRequest.request(url, { method: "POST", header: GameWebTool.gameCodeHeader });
    }

    /** 获取我的信息 */
    public static async getMyInfo(guildId: number) {
        let url = this.Url + `get_my_info?guildId=${guildId}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse<HttpGuildMatchModel.GuildMatchInfo>;
        if (result?.code == 0) {
            return result.data;
        } else {
            mLogger.error(result);
            return null;
        }
    }

    /** 获取小组排名(活动未开启返回上一届数据) */
    public static async getGroup(guildId: number) {
        let url = this.Url + `get_group?guildId=${guildId}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse<HttpGuildMatchModel.RspGuildMatchGroup>;
        if (result?.code == 0) {
            return result.data;
        } else {
            mLogger.error(result);
            return null;
        }
    }

    /** 获取全服排名(活动未开启返回上一届数据) */
    public static async getAll(topSize: number) {
        let url = this.Url + `get_all?topSize=${topSize}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse<HttpGuildMatchModel.RspGuildMatchAll>;
        if (result?.code == 0) {
            return result.data;
        } else {
            mLogger.error(result);
            return null;
        }
    }

    /** 增加排位赛积分 */
    public static addScore(guildId: number, score: number) {
        let url = this.Url + `add_score?guildId=${guildId}&score=${score}`;
        HttpRequest.request(url, { method: "POST", header: GameWebTool.gameCodeHeader });
    }

}