// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

/** 公告数据结构 */
declare namespace HttpNoticeModel {

   /** 公告数据 */
   export interface Notice {
       /** id */
       id?: string;
       /** 是否生效 */
       enable: boolean;
       /** 是否自动展示 */
       autoShow: boolean;
       /** 主题 */
       subject: string;
       /** 内容 */
       body: string;
       /** 附带奖励 */
       attachment?: string;
       /** 发送时间 */
       createTime?: number;
   }

}