// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

import { HttpRequest } from "../../../module/network/HttpRequest";
import { GameWebTool } from "../GameWebTool";

/** 排行榜接口 */
export class HttpLeaderboard {

    private static get Url() { return `${mGameSetting.serverUrl}/leaderboard/${mGameSetting.gameCode}/`; }

    /** 更新排行榜数据 */
    public static async updateLeaderboard(name: string, reqData: HttpLeaderboardModel.Leaderboard) {
        let url = this.Url + `update_leaderboard?name=${name}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", data: reqData, header: GameWebTool.gameCodeHeader }) as MResponse;
        if (result?.code == 0) {
            return true;
        } else {
            mLogger.error(result);
            return false;
        }
    }

    /** 获取排行榜数据 */
    public static async getLeaderboards(reqData: HttpLeaderboardModel.ReqLeaderboard) {
        let url = this.Url + `get_leaderboards`;
        let result = await HttpRequest.requestObject(url, { method: "POST", data: reqData, header: GameWebTool.gameCodeHeader }) as MResponse<HttpLeaderboardModel.LeaderboardInfo[]>;
        if (result?.code == 0) {
            return result.data;
        } else {
            mLogger.error(result);
            return null;
        }
    }

}