// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

/** 微信小游戏数据结构 */
declare namespace HttpWeChatModel {

   /** 请求 解密敏感数据 */
   export interface ReqWxBizData {
       /** 会话密钥 */
       session_key?: string;
       /** 通过wx.login接口获得临时登录凭证 */
       code?: string;
       /** 使用 sha1( rawData + sessionkey ) 得到字符串，用于校验用户信息 */
       signature: string;
       /** 包括 GameClubData 在内的加密数据，详见加密数据解密算法 */
       encryptedData: string;
       /** 加密算法的初始向量 */
       iv: string;
   }

   /** 请求 微信图片安全检测 */
   export interface ReqWxImageSecCheck {
       /** 为避免其它地方获取的accessToken失效,可以选择复用 */
       accessToken?: string;
       /** 用户的openid（用户需在近两小时访问过小程序） */
       openid: string;
       /** 场景枚举值（1 资料；2 评论；3 论坛；4 社交日志） */
       scene: number;
       /** 需检测的图片url */
       media_url: string;
   }

   /** 请求 微信文本安全检测 */
   export interface ReqWxMsgSecCheck {
       /** 为避免其它地方获取的accessToken失效,可以选择复用 */
       accessToken?: string;
       /** 用户的openid（用户需在近两小时访问过小程序） */
       openid: string;
       /** 场景枚举值（1 资料；2 评论；3 论坛；4 社交日志） */
       scene: number;
       /** 需检测的文本内容 */
       content: string;
   }

   /** 响应 获取微信AccessToken */
   export interface RspWxAccessToken {
       /** 获取到的凭证 */
       access_token?: string;
       /** 凭证有效时间，单位：秒。目前是7200秒之内的值。 */
       expires_in: number;
       /** 错误码 */
       errcode: number;
       /** 错误信息 */
       errmsg?: string;
   }

   /** 响应 微信解密数据 */
   export interface RspWxBizData {
       /** 会话密钥 */
       session_key: string;
       /** 解密后的原数据 */
       rawData: string;
   }

   /** 响应 微信登录 */
   export interface RspWxLogin {
       /** 用户唯一标识 */
       openid?: string;
       /** 会话密钥 */
       session_key?: string;
       /** 用户在开放平台的唯一标识符，若当前小程序已绑定到微信开放平台账号下会返回，详见 UnionID 机制说明 */
       unionid?: string;
   }

}