// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

import { HttpRequest } from "../../../module/network/HttpRequest";
import { GameWebTool } from "../GameWebTool";

/** 微信小游戏接口 */
export class HttpWeChat {

    private static get Url() { return `${mGameSetting.serverUrl}/wechatgame/${mGameSetting.gameCode}/`; }

    /** 登录 */
    public static async login(code: string) {
        let url = this.Url + `login?code=${code}`;
        let result = await HttpRequest.requestObject(url, { method: "POST", header: GameWebTool.gameCodeHeader }) as MResponse<HttpWeChatModel.RspWxLogin>;
        if (result?.code == 0) {
            return result.data;
        } else {
            mLogger.error(result);
            return null;
        }
    }

    /** 敏感数据解密 */
    public static async decryptBizData(reqData: HttpWeChatModel.ReqWxBizData) {
        let url = this.Url + `decrypt_bizdata`;
        let result = await HttpRequest.requestObject(url, { method: "POST", data: reqData, header: GameWebTool.gameCodeHeader }) as MResponse<HttpWeChatModel.RspWxBizData>;
        if (result?.code == 0) {
            return result.data;
        } else {
            mLogger.error(result);
            return null;
        }
    }

    /** 文本安全性校验 */
    public static async msgSecCheck(reqData: HttpWeChatModel.ReqWxMsgSecCheck) {
        let url = this.Url + `msg_sec_check`;
        let result = await HttpRequest.requestObject(url, { method: "POST", data: reqData, header: GameWebTool.gameCodeHeader }) as MResponse;
        if (result?.code == 0) {
            return true;
        } else {
            mLogger.error(result);
            return false;
        }
    }

    /** 图片安全性校验 */
    public static async imageSecCheck(reqData: HttpWeChatModel.ReqWxImageSecCheck) {
        let url = this.Url + `image_sec_check`;
        let result = await HttpRequest.requestObject(url, { method: "POST", data: reqData, header: GameWebTool.gameCodeHeader }) as MResponse;
        if (result?.code == 0) {
            return true;
        } else {
            mLogger.error(result);
            return false;
        }
    }

}