// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

/** 游戏后台数据结构 */
declare namespace HttpGwGameModel {

   /** 游戏后台游戏 */
   export interface GwGame {
       /** 游戏名 */
       name: string;
       /** 游戏渠道 */
       channels: string[];
   }

}