// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

/** 邮件数据结构 */
declare namespace HttpEmailModel {

   /** 邮件 */
   export interface Email {
       /** 邮件id 更新邮件时必传 */
       id?: string;
       /** 发件人ID */
       sender?: string;
       /** 收件人ID */
       receivers: string[];
       /** 邮件主题 */
       subject: string;
       /** 邮件内容 */
       body: string;
       /** 附带奖励 */
       attachment?: string;
       /** 邮件类型 */
       type?: string;
       /** 扩展参数 */
       extParam?: string;
       /** 发送时间(毫秒) */
       createTime?: number;
       /** 过期时间(毫秒 不填默认15天后过期) */
       expireTime?: number;
   }

}