// <auto-generated> This code was generated automatically. Do not modify. </auto-generated>

/** 兑换码数据结构 */
declare namespace HttpRedeemCodeModel {

   /** 兑换码数据 */
   export interface RedeemCode {
       /** 兑换码Code，唯一 */
       code: string;
       /** 奖励 */
       reward: string;
       /** 兑换次数限制 */
       maxCount?: number;
       /** 兑换码创建时间 */
       createTime: number;
       /** 兑换码生效时间 */
       activeTime: number;
       /** 兑换码过期时间 */
       expireTime: number;
   }

   /** 请求 生成兑换码 */
   export interface ReqGenRedeemCode {
       /** 兑换码Code 不填则自动生成 */
       code?: string;
       /** 奖励 */
       reward: string;
       /** 兑换次数限制 不填则无限制 */
       maxCount?: number;
       /** 生效时间 */
       activeTime: number;
       /** 过期时间 */
       expireTime: number;
   }

}